name: Sync Discussion to Markdown

on:
  push:
    branches:
      - main
    paths:
      - 'resources/notes/**'  # Trigger only when Markdown files in resources/notes/ change

jobs:
  sync:
    runs-on: ubuntu-latest
    container: rocker/r-ver:4.3.1  # Use a specific Rocker R version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          install.packages("httr", repos = "https://cloud.r-project.org/")

      - name: Run sync script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript scripts/sync_discussion_to_markdown.R